# .github/workflows/server-tests.yml
name: Server Unit Tests

on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml'
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml'

jobs:
  test-server:
    name: Run Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: pnpm test
