name: Client Unit Tests

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: pnpm test
